import type { Place } from '@/domain/entities/place.js';

/**
 * Datos de ejemplo para desarrollo y pruebas. Permiten que el frontend y la
 * API de consulta avancen sin depender de una corrida real contra Places API.
 * No representan establecimientos reales.
 *
 * Varios registros tienen `phoneNumber` o `website` vacios a proposito: en los
 * datos reales muchos lugares no los traen, y la UI debe distinguir desde el
 * inicio entre "campo ausente" y "error del sistema". Los campos vacios se
 * documentan, nunca se rellenan.
 *
 * Las keywords usan la forma de disciplina, no la agentiva, igual que el
 * catalogo de variantes: un establecimiento se llama "cardiologia", no
 * "cardiologo".
 */
const now = '2026-01-15T12:00:00.000Z';

export const SEED_PLACES: Place[] = [
  {
    placeId: 'seed_onc_z4_001',
    name: 'Centro Oncologico Zona 4',
    formattedAddress: '4a Avenida 12-34, Zona 4, Ciudad de Guatemala',
    specialty: 'oncology',
    zone: '4',
    phoneNumber: '+502 2222 1111',
    website: 'https://oncologico-z4.example.com',
    sourceKeyword: 'oncologia zona 4 Guatemala',
    createdAt: now,
    collectedAt: now,
  },
  {
    placeId: 'seed_onc_z4_002',
    name: 'Instituto de Cancerologia Central',
    formattedAddress: '7a Calle 5-20, Zona 4, Ciudad de Guatemala',
    specialty: 'oncology',
    zone: '4',
    phoneNumber: '+502 2222 2222',
    website: '',
    sourceKeyword: 'clinica oncologica zona 4 Guatemala',
    createdAt: now,
    collectedAt: now,
  },
  {
    placeId: 'seed_onc_z11_013',
    name: 'Oncologia Roosevelt',
    formattedAddress: 'Calzada Roosevelt 22-15, Zona 11, Ciudad de Guatemala',
    specialty: 'oncology',
    zone: '11',
    phoneNumber: '',
    website: '',
    sourceKeyword: 'oncologia zona 11 Guatemala',
    createdAt: now,
    collectedAt: now,
  },
  {
    placeId: 'seed_car_z10_003',
    name: 'Clinica Cardiologica del Valle',
    formattedAddress: '12 Calle 1-25, Zona 10, Ciudad de Guatemala',
    specialty: 'cardiology',
    zone: '10',
    phoneNumber: '+502 2333 4444',
    website: 'https://cardiologica-valle.example.com',
    sourceKeyword: 'clinica cardiologica zona 10 Guatemala',
    createdAt: now,
    collectedAt: now,
  },
  {
    placeId: 'seed_car_z10_004',
    name: 'Centro Cardiovascular Reforma',
    formattedAddress: 'Avenida La Reforma 10-15, Zona 10, Ciudad de Guatemala',
    specialty: 'cardiology',
    zone: '10',
    phoneNumber: '',
    website: 'https://cardiovascular-reforma.example.com',
    sourceKeyword: 'centro cardiovascular zona 10 Guatemala',
    createdAt: now,
    collectedAt: now,
  },
  {
    placeId: 'seed_ped_z1_005',
    name: 'Clinica Pediatrica Centro Historico',
    formattedAddress: '8a Avenida 3-12, Zona 1, Ciudad de Guatemala',
    specialty: 'pediatrics',
    zone: '1',
    phoneNumber: '+502 2444 5555',
    website: '',
    sourceKeyword: 'clinica pediatrica zona 1 Guatemala',
    createdAt: now,
    collectedAt: now,
  },
  {
    placeId: 'seed_ped_z18_006',
    name: 'Pediatria Zona 18',
    formattedAddress: '17 Calle 20-05, Zona 18, Ciudad de Guatemala',
    specialty: 'pediatrics',
    zone: '18',
    phoneNumber: '',
    website: '',
    sourceKeyword: 'pediatria zona 18 Guatemala',
    createdAt: now,
    collectedAt: now,
  },
  {
    placeId: 'seed_der_z15_007',
    name: 'Dermatologia Vista Hermosa',
    formattedAddress: 'Boulevard Vista Hermosa 23-40, Zona 15, Ciudad de Guatemala',
    specialty: 'dermatology',
    zone: '15',
    phoneNumber: '+502 2555 6666',
    website: 'https://dermatologia-vh.example.com',
    sourceKeyword: 'dermatologia zona 15 Guatemala',
    createdAt: now,
    collectedAt: now,
  },
  {
    placeId: 'seed_oft_z11_008',
    name: 'Clinica Oftalmologica Roosevelt',
    formattedAddress: 'Calzada Roosevelt 14-20, Zona 11, Ciudad de Guatemala',
    specialty: 'ophthalmology',
    zone: '11',
    phoneNumber: '+502 2666 7777',
    website: '',
    sourceKeyword: 'clinica oftalmologica zona 11 Guatemala',
    createdAt: now,
    collectedAt: now,
  },
  {
    placeId: 'seed_neu_z10_009',
    name: 'Centro de Neurociencias',
    formattedAddress: '6a Avenida 20-25, Zona 10, Ciudad de Guatemala',
    specialty: 'neurology',
    zone: '10',
    phoneNumber: '',
    website: '',
    sourceKeyword: 'centro de neurociencias zona 10 Guatemala',
    createdAt: now,
    collectedAt: now,
  },
  {
    placeId: 'seed_gen_z7_010',
    name: 'Centro de Salud Zona 7',
    formattedAddress: '25 Avenida 4-10, Zona 7, Ciudad de Guatemala',
    specialty: 'generalMedicine',
    zone: '7',
    phoneNumber: '+502 2777 8888',
    website: '',
    sourceKeyword: 'medicina general zona 7 Guatemala',
    createdAt: now,
    collectedAt: now,
  },
  {
    placeId: 'seed_gin_z9_011',
    name: 'Ginecologia y Obstetricia Zona 9',
    formattedAddress: 'Avenida La Reforma 8-60, Zona 9, Ciudad de Guatemala',
    specialty: 'gynecology',
    zone: '9',
    phoneNumber: '+502 2888 9999',
    website: 'https://gineco-z9.example.com',
    sourceKeyword: 'ginecologia zona 9 Guatemala',
    createdAt: now,
    collectedAt: now,
  },
  {
    placeId: 'seed_psi_z14_012',
    name: 'Salud Mental Zona 14',
    formattedAddress: '2a Avenida 15-30, Zona 14, Ciudad de Guatemala',
    specialty: 'psychiatry',
    zone: '14',
    phoneNumber: '',
    website: '',
    sourceKeyword: 'centro de salud mental zona 14 Guatemala',
    createdAt: now,
    collectedAt: now,
  },
];
